### ISSUE TITLE
'm' keyboard shortcut does not work when jump.js installed

### ISSUE THREAD

**Issue by jcamp** [denehyg/reveal.js-menu#33] opened 2017-03-24 17:44 UTC
As heading really.

When you have jump.js installed (allows you to enter a slide number and hit return to go to that slide) and the menu all still is good, but the 'm' keyboard shortcut does not work.

Could be an issue with jump.js or the menu I suppose, but worth a look to see an easy fix...

**Comment by denehyg** [comment] 2017-03-25 03:33
I can't reproduce this under Chrome, Firefox or Safari under macOS. If there is an issue I suspect it might be with jump.js as it overrides document.onkeypress directly rather than adding an event listener, but I'm not sure.

**Comment by jcamp** [comment] 2017-03-25 12:55
Thanks. Not sure which is more useful... m or typing in the number of the slide and hitting enter. Probably m keyboard so will not use jump.js for the moment. Cheers

**Comment by denehyg** [comment] 2018-02-08 10:14
I going to close this one. If you consider this to still be an issue feel free to reopen it.

**Closed by denehyg** 2018-02-08 10:14 UTC
